### ISSUE TITLE
Email template key

### ISSUE THREAD

**Issue by abdosaeedelhassan** [visualbuilder/email-templates#10]
i think email template key need to be selectable comes from config file  for next reasons:

1. important it used inside code so must be constant and not changing by end user.
2. i think every project contain there own email templates so this choice can let adding multiple email templates for each template key after that my later add an other choice to let end user select default template.

i can contribute this if i have a chance to do it.

**Comment by cannycookie** [comment]
Not sure I understand.  The key is used in the database so is queryable and dynamic, the users can create their own templates so why put the keys in the config?

**Comment by abdosaeedelhassan** [comment]
> Not sure I understand. The key is used in the database so is queryable and dynamic, the users can create their own templates so why put the keys in the config?

Your are correct this plugin work well for generating templates and there mailer, but the next step is make communication between these templates and project mail providers according for this i believe that every project has it owns email types and this plugin used to make email templates for this types.
