### ISSUE TITLE
Column missing from migrations

### ISSUE THREAD

**Issue by emjay64** [visualbuilder/email-templates#12]
Column not found: 1054 Unknown column 'logo_type' in 'field list'

**Comment by cannycookie** [comment]
Where does this happen?  logo_type is just a radio to define whether the user is uploading an image or pasting a url.   When i create or edit a template i don't get any errors.

**Comment by emjay64** [comment]
on edit template save changes, its attempting to save to 'logo_type' field
![image](https://github.com/user-attachments/assets/0f7ca1a5-393d-49ea-994f-faae10adc0dd)

**Comment by cannycookie** [comment]
It's odd because the tests also run on Laravel 11 and it doesn't throw an error.  I've unset the field before save so you should be OK now.  Just run composer update to get current version.

Best of luck

**Comment by emjay64** [comment]
Thank you!
This is a very neat package, very well done and professional looking templates, greatly appreciated!

**Comment by cannycookie** [comment]
Great!! So glad someone else is able to get some use from it.  Happy coding.
