### ISSUE TITLE
Email Template Resource Not Showing

### ISSUE THREAD

**Issue by sakthimanikandan845** [visualbuilder/email-templates#15]
In the left side navigation, only the "Email Template Theme" resource is showing, but the "Email Template" resource is not visible. I'm using this plugin in the Admin Panel provider, but it's still not working.

**Comment by murugans07** [comment]
> In the left side navigation, only the "Email Template Theme" resource is showing, but the "Email Template" resource is not visible. I'm using this plugin in the Admin Panel provider, but it's still not working.

same issue bro

**Comment by sakthimanikandan845** [comment]
I found an issue in the EmailTemplateResource file.

In the current resource file, both functions are incorrectly calling themes.label, but they should be calling templates.label. 
Here’s the incorrect code:

public static function getModelLabel(): string
{
    return config('filament-email-templates.navigation.themes.label');
}

public static function getPluralModelLabel(): string
{
    return config('filament-email-templates.navigation.themes.label');
}

The corrected version should be:

public static function getModelLabel(): string
{
    return config('filament-email-templates.navigation.templates.label');
}

public static function getPluralModelLabel(): string
    {
        return config('filament-email-templates.navigation.templates.label');
    }

Please make sure to update these functions accordingly.

**Comment by cannycookie** [comment]
This is fixed, apologies, i missed someone had changed this on a pull request.  Please run composer update and it should work

Regards
