### ISSUE TITLE
How to render blade in Graph API ?...

### ISSUE THREAD

**Issue by sakthimanikandan845** [visualbuilder/email-templates#20]
namespace App\Mail\Visualbuilder\EmailTemplates;

class GoalEmployee extends Mailable
{
    use Queueable, SerializesModels, BuildGenericEmail;
    public $template = 'goal-employee';
    public $sendTo;
    public function __construct($email)
    {
        $this->sendTo = $email;
    }

    public function build()
    {
       // Call the method to send email using Graph API
        $this->sendEmailUsingGraphAPI();

        return $this; // Return the Mailable instance
    }

    protected function sendEmailUsingGraphAPI()
    {
        $client = new Client();
        $token = $this->getAccessToken();

        $senderEmail = 'mymail@d.com';
        $url = "https://graph.microsoft.com/v1.0/users/$senderEmail/sendMail";

        // Render the email content using the Visualbuilder Email Template
        $body = View::make($this->template)->render();

        $emailData = [
            'message' => [
                'subject' => 'Your Goal Update',
                'body' => [
                    'contentType' => 'HTML',
                    'content' => $body,
                ],
                'toRecipients' => [
                    [
                        'emailAddress' => [
                            'address' => $this->sendTo,
                        ],
                    ],
                ],
            ],
        ];

**Okay, I'm currently using the Graph API to send emails with this plugin. It requires the body content to be a view**
        **$body = View::make($this->template)->render();**

        $emailData = [
            'message' => [
                'subject' => 'Your Goal Update',
                'body' => [
                    'contentType' => 'HTML',
                    **'content' => $body,**
                ],

**But I can't seem to find the Blade file using template key. Is it possible to apply this plugin with the Graph API?**

**Comment by cannycookie** [comment]
Sorry for the wait, there's an attribute on the EmailTemplate model:-

```php
    public function viewPath(): Attribute
    {
        return new Attribute(
            get: fn() => config('filament-email-templates.template_view_path') . '.' . $this->view
        );
    }
```

so you can use:-

```php
$this->emailTemplate = EmailTemplate::findEmailByKey($this->template, App::currentLocale());

$body = View::make($this->emailTemplate->view_path)->render();
```
