### ISSUE TITLE
Allow Resource Publishing

### ISSUE THREAD

**Issue by leek** [visualbuilder/email-templates#3]
Most Filament plugins give developers the ability to publish the plugins resources.

Example: https://github.com/3x1io/filament-user/blob/main/src/Console/PublishUserResourceCommand.php

This would allow developers to override the display (change where the navigation item shows up for example), etc.

Additionally, it would be nice if the plugin config was prefixed with `filament-`, which seems to be a convention amongst plugin authors.

**Comment by cannycookie** [comment]
The install command publishes the assets automatically so you don't have to do it.

**Comment by leek** [comment]
> The install command publishes the assets automatically so you don't have to do it.

It publishes the resource? This did not happen for me.

**Comment by cannycookie** [comment]
Oh, sorry I thought you meant the resource assets.  I can update it to publish the resource if you need it.  Will have a look over the weekend.

**Comment by Umar-Farooq-Shafi** [comment]
any updates?

**Comment by cannycookie** [comment]
Hi guys, 

Sorry, it's been a long time, have been juggling many balls.  The simplest solution is to create your own resource and extend the ```vendor/visualbuilder/email-templates/src/Resources/EmailTemplateResource.php``` file.
