### ISSUE TITLE
Hi i am getting an error when using multi tenancy that the route cannot be found

### ISSUE THREAD

**Issue by craigvc** [visualbuilder/email-templates#4]
Route [filament.agencySettings.email-templates] not defined.
we are using subdomain based multi tenancy if that makes a difference!
Any ideas how to fix it?
Also can we publish the templates folder?

**Comment by craigvc** [comment]
I solved the route issue, but I need to extend the model for the EmailTemplate

**Comment by cannycookie** [comment]
You can override the model using composer. https://stackoverflow.com/questions/60841930/laravel-6-7-how-can-i-override-change-a-vendor-class.

Templates should have been published when you run the install command.  Check here: resources/views/vendor/vb-email-templates/
